copyright = "Creative Commons by 4.0"
defaultContentLanguage = "en"
baseURL = "https://www.thiago.tech/"

pygmentsCodeFences = true

theme = "hugo-kiera"

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
    title = "Another nerdy blog"
    contentDir = "content/en"
    description = "Software Architecture and Engineering for the real world, and not only the hype framework"

  [languages.pt]
    weight = 2
    languageName = "Português"
    title = "Outro blog nerd"
    contentDir = "content/pt"
    description = "Engenharia e Arquitetura de Software para o mundo real, não só o framework da modinha"

  [languages.es]
    weight = 3
    languageName = "Español"
    title = "Otro blog nerd"
    contentDir = "content/es"
    description = "Ingeniería y diseño de software para el mundo real, no solamiente el framework del momiento"

[params]
  tagline = "With no bike-shed effect"

[author]
  name          = "Thiago Henrique"
  github        = "thiagohdeplima"
  linkedin      = "thiagohdeplima"
  twitter       = "thiagohdeplima"
  stackoverflow = "users/5036456/thiago-henrique"
